name: oil_skimmer
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  circular_seek_bar: ^1.1.1
  cloud_firestore: ^4.15.9
  firebase_core: ^2.27.1
  firebase_database: ^10.4.10
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  logger: ^1.4.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
 

flutter:
  uses-material-design: true
